### ISSUE TITLE
[IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3" using CLI Driver on MACOS

### ISSUE THREAD

**Issue by pwharned** [ibmdb/db2drivers#1]
Getting the above error code when trying to connect to a db2 database using the cli driver for macosx

I installed the Driver server package for mac osx from here https://epwt-www.mybluemix.net/software/support/trial/cst/programwebsite.wss?siteId=853&h=null&p=null

`db2cli execsql -connstring "DATABASE=bludb;HOSTNAME=localhost;PORT=50000;UID=db2inst1;PWD=password"`
```
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
SQLError: rc = 0 (SQL_SUCCESS)
SQLGetDiagRec: SQLState     : S1000
          fNativeError : -1042
          szErrorMsg   : [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

          cbErrorMsg   : 83
```
my PATH

/Applications/dsdriver/lib:/Applications/dsdriver/lib/icc:/Applications/dsdriver/adm:/Applications/dsdriver/bin:/Users/pat/.sdkman/candidates/scala/current/bin:/Users/pat/.sdkman/candidates/sbt/current/bin:/Users/pat/.sdkman/candidates/java/current/bin:/usr/local/opt/scala@2.12/bin:/usr/local/Caskroom/miniconda/base/envs/db2/bin:/usr/local/sbin:/usr/local/opt/openjdk/bin:/usr/local/Caskroom/miniconda/base/envs/flask/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/pat/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/sbin:/usr/local/opt/openjdk/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/pat/bin:/Users/pat/.local/bin:/usr/local/opt:/Users/pat/.sdkman/candidates

my DYLD_LIBRARY_PATH

/Applications/dsdriver/lib:/Applications/dsdriver/lib/icc

I can connect to the database using a python environment with ibm_db_sa with no trouble.

And most interestingly, i can fix this issue with the CLI driver by following these steps:

`export DYLD_LIBRARY_PATH=` # remove this variable
`export PATH=`/Users/pat/.sdkman/candidates/scala/current/bin:/Users/pat/.sdkman/candidates/sbt/current/bin:/Users/pat/.sdkman/candidates/java/current/bin:/usr/local/opt/scala@2.12/bin:/usr/local/Caskroom/miniconda/base/envs/db2/bin:/usr/local/sbin:/usr/local/opt/openjdk/bin:/usr/local/Caskroom/miniconda/base/envs/flask/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/pat/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/sbin:/usr/local/opt/openjdk/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/pat/bin:/Users/pat/.local/bin:/usr/local/opt:/Users/pat/.sdkman/candidates` #remove all references to the binaries and shared libraries in /Applications/dsdriver`
`cd /Applications/dsdriver/bin`
`conda activate db2` #activate my python environment where i have installed ibm_db_sa
`./db2cli execsql -connstring "DATABASE=rest;HOSTNAME=localhost;PORT=50000;UID=db2inst1;PWD=password"`
works

There appears to be some references to a shared library or dylib that are missing in the cli driver installation package for mac osx? Or perhaps some bug to do with the `db2profile` script?

**Comment by pwharned** [comment]
Okay I am realizing this is because you have to be in the directory - i thought I was being clever by exporting the path so I could call `db2cli` without having to `cd` into `/Applications/dsdriver/bin` - if you are in the directory it works 

i'd still be curious to know which specific libraries are missing from PATH or whatever that causes this

**Comment by bimalkjha** [comment]
@pwharned You should add `/Applications/dsdriver/bin:/Applications/dsdriver/lib` to PATH and DYLD_LIBRARY_PATH system environment variables. Thanks.
